export default `

  type Team {
    TeamId: Int!
    School: String!
    Name: String!
    Conference: String!
    Coach: String!
    Location: String!
    State: String!
    Abbreviation: String!
    Heisman: Heisman!
    SocialMedia: SocialMedia!
    Branding: Branding!
  }

  type SocialMedia {
    ADTwitter: String!
    FBTwitter: String!
    SBNTwitter: String!
    URL: String!
  }

  type Branding {
    Color: String!
    SecondaryColor: String!
    LikeColor: String!
  }

  # Base information about a schools Heismans 
  type Heisman {
    # This is the ID of the school
    TeamId: ID!
    # The name of the school
    School: String!
    # How many Heisman trophies the school has won
    Trophies: Int!
    # Any special comments about the trophies(looking at you USC)
    Special: String!
    # All of the winners
    HeismanWinners: [HeismanWinner]
  } 

  type HeismanWinner {
    # The year the Heisman was won
    Year: Int!
    # The name of the winner of the Heisman
    Winner: String!
    # The name of the school that the winner went to
    School: String!
    # The position the winner played on the field
    Position: String!
    # The number of points received during the voting
    Points: Int!
    # The percent of all points received by the winner during the voting
    PercentPointsPossible: String!
  }



  type Query {
    # Search by team for basic school information
    team(School: String!): Team
  }


`;
