export default DataTypes => ({
  id: DataTypes.INTEGER,
  TeamId: {
    type: DataTypes.INTEGER,
    primaryKey: true,
  },
  School: DataTypes.STRING,
  Slug: DataTypes.STRING,
  Wins: DataTypes.INTEGER,
  Losses: DataTypes.INTEGER,
  Ties: DataTypes.INTEGER,
  HomeWins: DataTypes.INTEGER,
  HomeLosses: DataTypes.INTEGER,
  HomeTies: DataTypes.INTEGER,
  Streak: DataTypes.INTEGER,
  StreakYears: DataTypes.STRING,
  CurrentStreak: DataTypes.INTEGER,
  CurrentStreakYears: DataTypes.STRING,
  Blowout: DataTypes.STRING,
  BlowoutYear: DataTypes.STRING,
  Total: DataTypes.INTEGER,
  Pct: DataTypes.FLOAT,
  HomePct: DataTypes.FLOAT,
  Recent: DataTypes.STRING,
  Special: DataTypes.STRING,
});
