export default `
  #Entry point in all team data
  type Team {
    #The name of the school
    School: String!
    #The nickname of the team
    Name: String!
    #The conference the team currently plays in
    Conference: String!
    #The current coach of the team
    Coach: String!
    #The city the team is located in
    Location: String!
    #The state the team is located in
    State: String!
    #The abbreviation for the team.
    Abbreviation: String!
    #Heisman related information about the team
    Heisman: Heisman!
    #Social media information about the team
    SocialMedia: SocialMedia!
    #Branding information about the team
    Branding: Branding!
    #All American information about the team
    AllAmerican: AllAmerican!
    #Choose the schools matchups for comparison
    Matchup: Matchup!
    #See how a team fares for all time rankings
    AllTimeRankings: AllTimeRankings!
  }

  #All American information about the team
  type AllAmerican {
    #The number of times the team has had someone as an All American
    Number: Int!
    #The number of players that have been voted as All Americans
    Players: Int!
  }
  
  #Branding information about the team
  type Branding {
    #The primary color for the team
    Color: String!
    #The seconday color for the team
    SecondaryColor: String!
    #The common color name for the team
    LikeColor: String!
  }

  #Social media information about the team
  type SocialMedia {
    #The Athletic Directors twitter account
    ADTwitter: String!
    #The football teams twitter account
    FBTwitter: String!
    #The Sports Blog Nation team twitter account
    SBNTwitter: String!
    #The URL of the team home page
    URL: String!
  }

  # Base information about a schools Heismans 
  type Heisman {
    # How many Heisman trophies the school has won
    Trophies: Int!
    # Any special comments about the trophies(looking at you USC)
    Special: String!
    # All of the winners
    HeismanWinners: [HeismanWinner]
  } 

  type HeismanWinner {
    # The year the Heisman was won
    Year: Int!
    # The name of the winner of the Heisman
    Winner: String!
    # The position the winner played on the field
    Position: String!
    # The number of points received during the voting
    Points: Int!
    # The percent of all points received by the winner during the voting
    PercentPointsPossible: String!
  }

  type Matchup {
    #The name of the competing school
    MatchupSchool: String!
    #Total Wins in Matchup by Team
    Wins: Int!
    #Total Losses in Matchup by Team
    Losses: Int!
    #Total Ties in Matchup by Team
    Ties: Int!
    #Team data for matchup team
    MatchupTeam: Team!
  }

  type AllTimeRankings {
    #Teams all time record rank compared to other teams
    AllTimeRecordRank: Int!
    #Teams all time record winning percent
    AllTimeRecordPercent: Float!
    #Teams all time record number of wins
    AllTimeRecordWins: Int!
    #Teams all time record number of losses
    AllTimeRecordLosses: Int!
    #Teams all time record number of ties
    AllTimeRecordTies: Int!
    #Teams number of national championships rank compared to other teams
    NationalChampRank: Int!
    #Teams number of national championships
    NationalChampData: Int!
    #Teams number of conference championships rank compared to other teams
    ConferenceChampRank: Int!
    #Teams number of conference championships
    ConferenceChampData: Int!
    #Teams all time bowl record rank compared to other teams
    BowlGameRank: Int!
    WinRank: Int!
    WinData: Int!
    BowlRecordRank: Int!
    BowlRecordPercent: Float!
    BowlRecordWins: Int!
    BowlRecordLosses: Int!
    BowlRecordTies: Int!
    AllAmericanRank: Int!
    AllAmericanData: Int!
    HeismanRank: Int!
    HeismanData: Int!
    NFLDraftRank: Int!
    NFLDraftData: Int!
    NFLFirstRoundRank: Int!
    NFLFirstRound: Int!
    APOneRank: Int!
    APOne: Int!
    WeeksInPollRank: Int!
    WeeksInPollData: Int!
    Overall: Float!
    OverallRank: Int!
    BowlStreakRank: Int!
    BowlStreakData: Int!
  }

#Queries on College Football
  type Query {
    # Search by team for basic school information
    team(School: String!, Matchup: String): Team,
  }
`;
