export default (sequelize, DataTypes) => {
  const Rank = sequelize.define('Rank', {
    TeamId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
    },
    School: DataTypes.STRING,
		AllTimeRecordRank: DataTypes.INTEGER,
    AllTimeRecordPercent: DataTypes.FLOAT,
    AllTimeRecordWins: DataTypes.INTEGER,
    AllTimeRecordLosses: DataTypes.INTEGER,
    AllTimeRecordTies: DataTypes.INTEGER,
    NationalChampRank: DataTypes.INTEGER,
    NationalChampData: DataTypes.INTEGER,
    ConferenceChampRank: DataTypes.INTEGER,
    ConferenceChampData: DataTypes.INTEGER,
    BowlGameRank: DataTypes.INTEGER,
    WinRank: DataTypes.INTEGER,
    WinData: DataTypes.INTEGER,
    BowlRecordRank: DataTypes.INTEGER,
    BowlRecordPercent: DataTypes.FLOAT,
    BowlRecordWins: DataTypes.INTEGER,
    BowlRecordLosses: DataTypes.INTEGER,
    BowlRecordTies: DataTypes.INTEGER,
    AllAmericanRank: DataTypes.INTEGER,
    AllAmericanData: DataTypes.INTEGER,
    HeismanRank: DataTypes.INTEGER,
    HeismanData: DataTypes.INTEGER,
    NFLDraftRank: DataTypes.INTEGER,
    NFLDraftData: DataTypes.INTEGER,
    NFLFirstRoundRank: DataTypes.INTEGER,
    NFLFirstRound: DataTypes.INTEGER,
    APOneRank: DataTypes.INTEGER,
    APOne: DataTypes.INTEGER,
    WeeksInPollRank: DataTypes.INTEGER,
    WeeksInPollData: DataTypes.INTEGER,
    Overall: DataTypes.FLOAT,
    OverallRank: DataTypes.INTEGER,
    BowlStreakRank: DataTypes.INTEGER,
    BowlStreakData: DataTypes.INTEGER,
  });
  return Rank;
};
